### ISSUE TITLE
Error: Incompatible parameters specified in the request: mine, channelId

### ISSUE THREAD

**Issue by tombatossals** [cedricdelpoux/gatsby-source-youtube#3]
Hello there!

I've tried to use "gatsby-source-youtube" to fecth the videos from my channel. I followed the instructions about setting the oauth_client_id, oauth_client_secret and youtube_token inside my .env file. But when I try to start the project I get the following message shown in the screenshot.

<img width="1303" alt="Captura de pantalla 2020-12-04 a las 16 22 03" src="https://user-images.githubusercontent.com/124169/101181469-338a1080-364d-11eb-878b-fdcfff923d46.png">

Any idea what I'm doing wrong?

Thanks

**Comment by cedricdelpoux** [comment]
Hi @tombatossals, thank you for reporting this. Could you share your gatsby config?

**Comment by tombatossals** [comment]
Yess @cedricdelpoux thanks for the reply. Here's the relevant part of the config:

`...   
   {
      resolve: "gatsby-source-youtube",
      options: {
        channelId: "UCno5DiyUfXItc9vl34fYGgw",
        debug: true,
      },
    },
  ...
`

**Comment by cedricdelpoux** [comment]
I fixed the issue in `2.3.1` version.

But you will have 0 videos because for now I fetch videos from playlist only. 
I need to support videos fetching outside playlists. 

For now, I suggest you to add your video in a playlist on Youtube. If the video is yours, you don't need to add `channelId: "UCno5DiyUfXItc9vl34fYGgw"` option because the plugin fetch from your playlist directly

**Comment by tombatossals** [comment]
Working like a charm right now.

Thanks for your help
